### ISSUE TITLE
Weird random positioning in group when categoryId is null

### ISSUE THREAD

**Issue by iurijacob** [yii2tech/ar-position#1]
When trying to position in a null category group I'm getting the following result:

Initial position:
Item 1 -> position 1

After adding item 2:
Item 1 -> position 0
Item 2 -> position 1

Update item 2 for the first time:
Item 1 -> position 0
Item 2 -> position 2

Update item 2 for the second time:
Item 1 -> position 0
Item 2 -> position 0

Solved this issue by changing the line 256 of PositionBehavior.php to this code:

``` php
$condition[$attribute] = empty($this->owner->$attribute)?null:$this->owner->$attribute;
```

**Comment by iurijacob** [comment]
Solved #2

**Comment by klimov-paul** [comment]
Empty value for the attribute not always means it is actually `null`. For example: `0` value can be a valid one.

I assume you have this problem, because you collect group attribute data from a web form. 
You should setup a filter validator, which will typecast empty string ('') into `null` in such case.

**Comment by iurijacob** [comment]
Actually my group attribute is a nullable foreign key, which means that some entities have a category and some not, and it will never have a `0` value.

But I used `empty()` instead of `is_null()` because for some reason the line `$this->owner->$attribute;` was returning an empty string, not a `null` value as it was supposed to, based on my db data.

Anyway, You´re right, It´s still a bug. I'll figure out a solution for the zero's case.

**Comment by iurijacob** [comment]
`0` is not the same as empty, though php evaluates that way. But even assuming it's the same, your code should handle with this instead of behaving randomly.

By the way, my group attribute is not coming from a web form, it's a foreign key.

**Comment by klimov-paul** [comment]
> it's the same, your code should handle with this instead of behaving randomly.

Seems you are not paying attention: you are not only developer in this world, remember?
For someone else values like `0` or empty string `` can be considered as valid, and their typecast is not desiarable.

> my group attribute is not coming from a web form, it's a foreign key.

Then how it becomes empty, but NOT `null`?
If the group attribute value is set to `null` it is handled correctly. You should check your code, so it ensures empty value conversion or correct `null` setup.

**Comment by iurijacob** [comment]
> Then how it becomes empty, but NOT null?

It's a good question. Maybe you are right, Maybe I have a bug in my code. But it flees entirely to the main subject. your code doesn´t handle well with empty values. Period.

> Seems you are not paying attention: you are not only developer in this world, remember?

Really? keep your buggy code then.
What a waste of time...
