### ISSUE TITLE
Position is not updated when deleting the record

### ISSUE THREAD

**Issue by glpzzz** [yii2tech/ar-position#10]
I have checked the code for PositionBehavior::beforeDelete and the idea (moveLast()) is great, but it seems not to be working. 

### What steps will reproduce the problem?
Delete a record

### What is the expected result?
Position of other elementos to be updated

### What do you get instead?
Elements that were after the deleted record keeps their position. I have elements in positions 1 to 10, if deleting the 2nd the third should become 2nd and the same for the rest.

### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | "yii2tech/ar-position": "^1.0"
| Yii Framework Version | "yiisoft/yii2": "~2.0.6",
| PHP version           | PHP 7.2.19-0ubuntu0.19.04.2 (cli) (built: Aug 13 2019 11:45:23) ( NTS )
| Operating system      | Linux  Ubuntu 19.04 5.3.0-050300rc7-generic #201909021831 SMP Mon Sep 2 18:33:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klimov-paul** [comment]
Unable to reproduce.
I have added a unit test to verify `delete()` is working correctly:
b0e4e85196e1729cbb8c7a9fcef5c984de42223e

**Comment by glpzzz** [comment]
Thanks. I test again! 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by glpzzz** [comment]
@klimov-paul my bad. 

I set the behavior in a record that represents a row in a junction table. The relation is set with the viaTable method. When using ActiveRecord::link and unlink, it doesn't instantiate the ActiveRecord instance for the row in the junction table, so events are not called. 

I don't see any way to make it work other than instantiating the junction row as ActiveRecord and calling save (to create) or delete. The shortcut provided by link and unlink is not useful here.

The behavior works as expected!
