### ISSUE TITLE
How to handle categories coming from a junction table?

### ISSUE THREAD

**Issue by bigbrush** [yii2tech/ar-position#3]

**Comment by klimov-paul** [comment]
What do you mean?

**Comment by bigbrush** [comment]
Let me try to make more sense. I have 3 models: `Product`, `ProductCategory` and `ProductCategoryJunction`. Each `Product` can be assigned to multiple categories by using `ProductCategoryJunction` model.

Is it possible to setup/extend this behavior to handle multiple categories for a product where the table column doesn't exist in `Product` but in `ProductCategoryJunction`?

**Comment by klimov-paul** [comment]
You should create a model for `ProductCategoryJunction` table, put position column there and attach behavior to this model.

**Comment by bigbrush** [comment]
Thanks, i will try it out.
