### ISSUE TITLE
Allow to set group attribute value directry

### ISSUE THREAD

**Issue by AnatolyRugalev** [yii2tech/ar-position#4]
We are facing problem when using `PositionBehavior` in couple with `SoftDeleteBehavior`.

We want to exclude deleted records from `updateAllCounters` update:

``` php
public function behaviors() {
    return [
        'softDelete' => [
            'class' => SoftDeleteBehavior::className(),
            'softDeleteAttributeValues' => [
                'isDeleted' => true,
            ],
        ],
        'position' => [
            'class' => PositionBehavior::className(),
            'positionAttribute' => 'position',
            'groupAttributes' => [
                'albumListId',
                'isDeleted',
            ],
        ],
    ];
}
```

But this causes that `PositionBehavior` updates only deleted records. Yes, I know that changing behaviors order may solve this problem, but this is not a good idea.

I propose adding ability to set a value into `groupAttributes` like that:

``` php
'groupAttributes' => [
    'albumListId',
    'isDeleted' => false,
]
```

Thank you.

**Comment by klimov-paul** [comment]
I am unsure, what excactly you problem is.
Please answer the following questions first:

1) What steps will reproduce the problem?

2) What is the expected result?

3) What do you get instead?

**Comment by klimov-paul** [comment]
Closed unless more information provided.

Note: using `ar-softdelete` you can handle `beforeSoftDelete` event in order to prevent inconsistencies with `ar-position` behavior.
