### ISSUE TITLE
First and last checkers need

### ISSUE THREAD

**Issue by agilov** [yii2tech/ar-position#6]
Please add feature to check if model is first or last in position
isFirst and isLast methods

**Comment by agilov** [comment]
or it can be getNextRecord and getPrevRecord as well.

you can wrap this code  $nextRecord = $this->owner->find()
            ->andWhere($this->createGroupConditionAttributes())
            ->andWhere([$positionAttribute => ($this->owner->$positionAttribute + 1)])
            ->one();
in method.

**Comment by klimov-paul** [comment]
Resolved by commit f56e9d39da9190a85eaadef67021fd7d35b44d07
