### ISSUE TITLE
[ENH] Add new property `insertDefaultPosition`

### ISSUE THREAD

**Issue by ARHImed82** [yii2tech/ar-position#7]
As I undestand all new records are appended to the end of list when `positionAttribute` is empty in insert scenario.
Is it a good idea to add a new property (for example `insertDefaultPosition`) when we can choose default inserting position (first or last or even exactly integer position).

**Comment by klimov-paul** [comment]
https://github.com/yii2tech/ar-position/blame/master/README.md#L89-L99
