### ISSUE TITLE
Update groupAttribute

### ISSUE THREAD

**Issue by zazoley** [yii2tech/ar-position#9]
When I update groupAttribute behavior put old position to $this->positionOnSave in beforeUpdate event and then saves it in afterSave event instead of keeping the new calculated position (line 435).
I believe there is a wrong unnecessary line:

https://github.com/yii2tech/ar-position/blob/0822f8b6a3b7df0404115591c08a21bf53b37b38/PositionBehavior.php#L430

**Comment by klimov-paul** [comment]
No, current behavior is correct.
If you move the item, which is first at group 'A' to the group 'B', it is expected this item remains to be first - not last.
